"""
Analyze persona-conditioned reward model scores generated by
generate_persona_reward_model_scores.py.

Compares each (model, template, persona) ranking against the matching neutral
baseline ranking (data/reward_model_scores/<model>.csv) using Kendall's tau,
Spearman's rho, and Rank-Biased Overlap (RBO) at several p values — the same
metrics used in analysis_support.py for the original paper's model-vs-model
comparisons, applied here to persona-vs-baseline instead.

Outputs (persona_analysis/output/):
  - summary_correlations.csv   one row per (model, template, persona): tau, rho, RBO@{0.9,0.95,0.99}
                                vs. the neutral baseline, plus lm_* counterparts (same metrics between
                                the base LM's own persona-conditioned logits and its own neutral
                                baseline) when data/base_model_logits/ and data/persona_base_model_logits/
                                have a matching file for that reward model's base_lm (config/reward_models.yaml)
  - rank_shifts.csv            long-format top movers (token rank change vs baseline) per persona,
                                deduplicated by token_decoded and tagged with direction (up/down)
  - top_bottom_tokens.csv      long-format top-5/bottom-5 raw-scored tokens per persona (Table 2/3 style)
  - template_pair_correlations.csv   one row per (model, persona, template_a, template_b): tau, rho,
                                RBO@{0.9,0.95,0.99} directly between two templates' persona-conditioned
                                rankings (not vs. baseline) — only for template pairs sharing a
                                `group` (persona_prompts.yaml), i.e. different framings of "the same" question
  - template_pair_rank_shifts.csv   long-format top-10 movers per (model, persona, template_a,
                                template_b): tokens whose rank shifted most between the two
                                templates' persona-conditioned rankings, deduplicated by
                                token_decoded and tagged with direction (up/down)
  - fig_kendall_tau_by_persona.png   bar chart of tau by persona, faceted by model x template
  - fig_tau_vs_rbo.png               scatter of tau vs RBO(p=0.95) — flags high-tau/low-RBO or
                                      low-tau/high-RBO personas (see project notes)
  - fig_rank_shift_example.png       Fig-5-style rank-shift bar chart for the most-divergent persona
"""
import itertools
import re
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yaml
from scipy.stats import kendalltau, spearmanr

sys.path.insert(0, str(Path(__file__).parent.parent))

ROOT = Path(__file__).parent.parent
CONFIG_DIR = ROOT / 'config'
DATA_DIR = ROOT / 'data'
OUTPUT_DIR = Path(__file__).parent / 'output'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(DATA_DIR / 'persona_reward_model_scores'))
import reassemble
reassemble.ensure_all()

with open(CONFIG_DIR / 'reward_models.yaml') as f:
    model_configs = yaml.safe_load(f)

with open(CONFIG_DIR / 'persona_prompts.yaml') as f:
    templates = yaml.safe_load(f)['templates']

with open(CONFIG_DIR / 'llama_base_models.yaml') as f:
    llama_base_models = yaml.safe_load(f)
llama_base_model_by_name = {m['name']: m for m in llama_base_models}

templates_by_group = defaultdict(list)
for _tname, _tinfo in templates.items():
    templates_by_group[_tinfo['group']].append(_tname)

with open(CONFIG_DIR / 'personas.yaml') as f:
    personas = yaml.safe_load(f)['personas']
persona_by_slug = {}


def slugify(text):
    text = text.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")


def format_token_label(token_decoded):
    """Make a decoded token safe/legible as a plot or table label.

    Distinct tokens frequently decode to strings that differ only in leading/
    trailing whitespace (e.g. BPE's "Ġ"-prefixed space marker) — real, distinct
    tokens that are kept separate everywhere upstream (joins are on token_id,
    dedup is on the exact token_decoded string), but whitespace collapses
    invisibly in both matplotlib labels and HTML, making them look like
    duplicate rows. Render whitespace visibly instead of stripping it.
    """
    if pd.isna(token_decoded):
        return '<NA>'
    s = str(token_decoded)
    if s == '':
        return '<empty>'
    if s.strip(' ') == '':
        return '␣' * len(s)
    leading = len(s) - len(s.lstrip(' '))
    trailing = len(s) - len(s.rstrip(' '))
    core = s[leading:len(s) - trailing] if trailing else s[leading:]
    core = core.replace('\n', '\\n').replace('\t', '\\t').replace('\r', '\\r')
    return ('␣' * leading) + core + ('␣' * trailing)


for p in personas:
    persona_by_slug[slugify(p['name'])] = p


def rbo(list1, list2, p=0.9, depth=None):
    """Rank-Biased Overlap between two ranked lists (already sorted best-first).

    Tracks the running overlap incrementally (O(n)) rather than recomputing a
    full set intersection at every depth (O(n^2)), which is intractable at
    full-vocabulary depth (~100k+ tokens).
    """
    if depth is None:
        depth = min(len(list1), len(list2))
    list1, list2 = list1[:depth], list2[:depth]
    seen1, seen2 = set(), set()
    overlap = 0
    total = 0.0
    for d in range(depth):
        item1, item2 = list1[d], list2[d]
        if item1 == item2:
            overlap += 1
        else:
            if item1 in seen2:
                overlap += 1
            if item2 in seen1:
                overlap += 1
        seen1.add(item1)
        seen2.add(item2)
        total += (overlap / (d + 1)) * (p ** d)
    return (1 - p) * total


# ---------------------------------------------------------------------------
# Load data & compute correlations
# ---------------------------------------------------------------------------
summary_rows = []
rank_shift_rows = []
top_bottom_rows = []
baseline_top_bottom_rows = []
template_pair_rows = []
template_pair_rank_shift_rows = []

for model_info in model_configs:
    model_name = model_info['name']
    nickname = model_info['nickname']
    safe_name = model_name.replace('/', '--')

    baseline_path = DATA_DIR / 'reward_model_scores' / f"{safe_name}.csv"
    persona_path = DATA_DIR / 'persona_reward_model_scores' / f"{safe_name}.csv"

    if not baseline_path.exists() or not persona_path.exists():
        print(f"Skipping {model_name} — missing baseline or persona data")
        continue

    baseline_df = pd.read_csv(baseline_path)
    persona_df = pd.read_csv(persona_path)

    # --- Base-LM lineage lookup, for the RM-vs-LM persona-sensitivity comparison ---
    # lm_baseline_df/lm_persona_df stay None (and the lm_* summary columns stay NaN)
    # until data/base_model_logits/ and data/persona_base_model_logits/ both have a
    # file for this reward model's base_lm — neither exists yet as of this writing.
    lm_name = model_info.get('base_lm')
    lm_baseline_df = None
    lm_persona_df = None
    if lm_name is not None and lm_name in llama_base_model_by_name:
        lm_safe_name = lm_name.replace('/', '--')
        lm_baseline_path = DATA_DIR / 'base_model_logits' / f"{lm_safe_name}.csv"
        lm_persona_path = DATA_DIR / 'persona_base_model_logits' / f"{lm_safe_name}.csv"
        if lm_baseline_path.exists() and lm_persona_path.exists():
            lm_baseline_df = pd.read_csv(lm_baseline_path)
            lm_persona_df = pd.read_csv(lm_persona_path)
        else:
            print(f"  (no base-LM logit data yet for {lm_name} — lm_* columns will be blank for {model_name})")

    persona_columns = [c for c in persona_df.columns
                        if c not in ('token_id', 'token_name', 'token_decoded')]

    warned_missing_baseline_cols = set()
    for col in persona_columns:
        template_name, _, persona_slug = col.partition('__')
        if template_name not in templates or persona_slug not in persona_by_slug:
            continue

        baseline_col = templates[template_name]['baseline_column']
        if baseline_col not in baseline_df.columns:
            if baseline_col not in warned_missing_baseline_cols:
                print(f"  Skipping template '{template_name}' — baseline column "
                      f"'{baseline_col}' not yet in {baseline_path.name}")
                warned_missing_baseline_cols.add(baseline_col)
            continue

        persona_meta = persona_by_slug[persona_slug]

        # Join on token_id (unique per tokenizer), not token_decoded — many
        # distinct token_ids can decode to the same string (e.g. whitespace
        # variants), which would silently blow up a token_decoded join.
        merged = baseline_df[['token_id', 'token_decoded', baseline_col]].merge(
            persona_df[['token_id', col]], on='token_id'
        ).dropna()

        tau, tau_p = kendalltau(merged[baseline_col], merged[col])
        rho, rho_p = spearmanr(merged[baseline_col], merged[col])

        baseline_ranked = merged.sort_values(baseline_col, ascending=False)['token_decoded'].tolist()
        persona_ranked = merged.sort_values(col, ascending=False)['token_decoded'].tolist()

        rbo_scores = {p: rbo(baseline_ranked, persona_ranked, p=p) for p in (0.9, 0.95, 0.99)}

        # --- Base-LM counterpart: same persona-shift computation, but between the
        # base LM's own persona-conditioned logits and its own neutral baseline,
        # so it's directly comparable to the reward model's tau/rho/RBO above.
        lm_tau = lm_tau_p = lm_rho = lm_rho_p = lm_n_tokens = None
        lm_rbo_scores = {0.9: None, 0.95: None, 0.99: None}
        if (lm_persona_df is not None and lm_baseline_df is not None
                and col in lm_persona_df.columns and baseline_col in lm_baseline_df.columns):
            lm_merged = lm_baseline_df[['token_id', baseline_col]].merge(
                lm_persona_df[['token_id', col]], on='token_id'
            ).dropna()
            if not lm_merged.empty:
                lm_tau, lm_tau_p = kendalltau(lm_merged[baseline_col], lm_merged[col])
                lm_rho, lm_rho_p = spearmanr(lm_merged[baseline_col], lm_merged[col])
                lm_baseline_ranked = lm_merged.sort_values(baseline_col, ascending=False)['token_id'].tolist()
                lm_persona_ranked = lm_merged.sort_values(col, ascending=False)['token_id'].tolist()
                lm_rbo_scores = {p: rbo(lm_baseline_ranked, lm_persona_ranked, p=p) for p in (0.9, 0.95, 0.99)}
                lm_n_tokens = len(lm_merged)

        summary_rows.append({
            'model': model_name,
            'model_nickname': nickname,
            'template': template_name,
            'persona': persona_meta['name'],
            'persona_category': persona_meta['category'],
            'n_tokens': len(merged),
            'kendall_tau': tau,
            'kendall_p': tau_p,
            'spearman_rho': rho,
            'spearman_p': rho_p,
            'rbo_p0.90': rbo_scores[0.9],
            'rbo_p0.95': rbo_scores[0.95],
            'rbo_p0.99': rbo_scores[0.99],
            'lm_available': lm_tau is not None,
            'lm_n_tokens': lm_n_tokens,
            'lm_kendall_tau': lm_tau,
            'lm_kendall_p': lm_tau_p,
            'lm_spearman_rho': lm_rho,
            'lm_spearman_p': lm_rho_p,
            'lm_rbo_p0.90': lm_rbo_scores[0.9],
            'lm_rbo_p0.95': lm_rbo_scores[0.95],
            'lm_rbo_p0.99': lm_rbo_scores[0.99],
        })

        # --- Rank-shift analysis (Fig 5 style) ---
        # Many distinct token_ids decode to the same display string (whitespace
        # variants etc.) — dedupe by token_decoded for presentation so the same
        # string doesn't appear to repeat itself in a "top movers" list.
        merged['baseline_rank'] = merged[baseline_col].rank(ascending=False, method='average')
        merged['persona_rank'] = merged[col].rank(ascending=False, method='average')
        merged['rank_diff'] = merged['persona_rank'] - merged['baseline_rank']
        deduped = merged.drop_duplicates(subset='token_decoded', keep='first')

        moved_up = deduped.sort_values('rank_diff').head(10)      # better rank under persona
        moved_down = deduped.sort_values('rank_diff', ascending=False).head(10)  # worse rank under persona

        for direction, group in (('up', moved_up), ('down', moved_down)):
            for _, row in group.iterrows():
                rank_shift_rows.append({
                    'model': model_name,
                    'model_nickname': nickname,
                    'template': template_name,
                    'persona': persona_meta['name'],
                    'persona_category': persona_meta['category'],
                    'direction': direction,
                    'token_decoded': row['token_decoded'],
                    'baseline_rank': row['baseline_rank'],
                    'persona_rank': row['persona_rank'],
                    'rank_diff': row['rank_diff'],
                })

        # --- Top-5 / bottom-5 raw tokens under this persona's prompt (Table 2/3 style) ---
        deduped_by_score = merged.drop_duplicates(subset='token_decoded', keep='first').sort_values(col, ascending=False)
        top5 = deduped_by_score.head(5)
        bottom5 = deduped_by_score.tail(5).iloc[::-1]  # worst-first

        for group_name, group in (('top', top5), ('bottom', bottom5)):
            for rank_in_group, (_, row) in enumerate(group.iterrows(), start=1):
                top_bottom_rows.append({
                    'model': model_name,
                    'model_nickname': nickname,
                    'template': template_name,
                    'persona': persona_meta['name'],
                    'persona_category': persona_meta['category'],
                    'group': group_name,
                    'rank_in_group': rank_in_group,
                    'token_decoded': row['token_decoded'],
                    'score': row[col],
                    'baseline_rank': row['baseline_rank'],
                })

    # --- Template-pair correlations (prompt-framing comparison) ---
    # Compares two templates' persona-conditioned rankings directly against each
    # other (not each vs. the neutral baseline) — only within groups of templates
    # that share a `group` (persona_prompts.yaml), i.e. framings of "the same"
    # underlying question. Robust to more templates being added to either group later.
    for question_group, template_group in templates_by_group.items():
        if len(template_group) < 2:
            continue
        for t1, t2 in itertools.combinations(template_group, 2):
            for persona_slug, persona_meta in persona_by_slug.items():
                col1 = f"{t1}__{persona_slug}"
                col2 = f"{t2}__{persona_slug}"
                if col1 not in persona_df.columns or col2 not in persona_df.columns:
                    continue

                pair_merged = persona_df[['token_id', 'token_decoded', col1, col2]].dropna()
                if pair_merged.empty:
                    continue

                p_tau, p_tau_p = kendalltau(pair_merged[col1], pair_merged[col2])
                p_rho, p_rho_p = spearmanr(pair_merged[col1], pair_merged[col2])
                ranked1 = pair_merged.sort_values(col1, ascending=False)['token_id'].tolist()
                ranked2 = pair_merged.sort_values(col2, ascending=False)['token_id'].tolist()
                p_rbo = {p: rbo(ranked1, ranked2, p=p) for p in (0.9, 0.95, 0.99)}

                template_pair_rows.append({
                    'model': model_name,
                    'model_nickname': nickname,
                    'question_group': question_group,
                    'template_a': t1,
                    'template_b': t2,
                    'persona': persona_meta['name'],
                    'persona_category': persona_meta['category'],
                    'n_tokens': len(pair_merged),
                    'kendall_tau': p_tau,
                    'kendall_p': p_tau_p,
                    'spearman_rho': p_rho,
                    'spearman_p': p_rho_p,
                    'rbo_p0.90': p_rbo[0.9],
                    'rbo_p0.95': p_rbo[0.95],
                    'rbo_p0.99': p_rbo[0.99],
                })

                # --- Token-level rank-shift detail between the two templates, for the
                # heatmap-cell drilldown. Same convention as the persona-vs-baseline
                # rank-shift analysis above, but between two persona-conditioned columns.
                pair_merged['template_a_rank'] = pair_merged[col1].rank(ascending=False, method='average')
                pair_merged['template_b_rank'] = pair_merged[col2].rank(ascending=False, method='average')
                pair_merged['rank_diff'] = pair_merged['template_b_rank'] - pair_merged['template_a_rank']
                pair_deduped = pair_merged.drop_duplicates(subset='token_decoded', keep='first')

                pair_moved_up = pair_deduped.sort_values('rank_diff').head(10)
                pair_moved_down = pair_deduped.sort_values('rank_diff', ascending=False).head(10)

                for direction, group in (('up', pair_moved_up), ('down', pair_moved_down)):
                    for _, row in group.iterrows():
                        template_pair_rank_shift_rows.append({
                            'model': model_name,
                            'model_nickname': nickname,
                            'question_group': question_group,
                            'template_a': t1,
                            'template_b': t2,
                            'persona': persona_meta['name'],
                            'persona_category': persona_meta['category'],
                            'direction': direction,
                            'token_decoded': row['token_decoded'],
                            'template_a_rank': row['template_a_rank'],
                            'template_b_rank': row['template_b_rank'],
                            'rank_diff': row['rank_diff'],
                        })

    # --- Baseline (no-persona) top-5/bottom-5 tokens, for direct comparison ---
    # One per baseline_column actually used by a template (e.g. 'greatest', 'worst'),
    # independent of any persona — this is what the model prefers with no prefix at all.
    used_baseline_cols = {t['baseline_column'] for t in templates.values()}
    for baseline_col in used_baseline_cols:
        if baseline_col not in baseline_df.columns:
            continue
        deduped_baseline = baseline_df[['token_decoded', baseline_col]].dropna() \
            .drop_duplicates(subset='token_decoded', keep='first').sort_values(baseline_col, ascending=False)
        top5 = deduped_baseline.head(5)
        bottom5 = deduped_baseline.tail(5).iloc[::-1]
        for group_name, group in (('top', top5), ('bottom', bottom5)):
            for rank_in_group, (_, row) in enumerate(group.iterrows(), start=1):
                baseline_top_bottom_rows.append({
                    'model': model_name,
                    'model_nickname': nickname,
                    'baseline_column': baseline_col,
                    'group': group_name,
                    'rank_in_group': rank_in_group,
                    'token_decoded': row['token_decoded'],
                    'score': row[baseline_col],
                })

summary_df = pd.DataFrame(summary_rows)
rank_shift_df = pd.DataFrame(rank_shift_rows)
top_bottom_df = pd.DataFrame(top_bottom_rows)
baseline_top_bottom_df = pd.DataFrame(baseline_top_bottom_rows)
template_pair_df = pd.DataFrame(template_pair_rows)
template_pair_rank_shift_df = pd.DataFrame(template_pair_rank_shift_rows)

summary_df.to_csv(OUTPUT_DIR / 'summary_correlations.csv', index=False)
rank_shift_df.to_csv(OUTPUT_DIR / 'rank_shifts.csv', index=False)
top_bottom_df.to_csv(OUTPUT_DIR / 'top_bottom_tokens.csv', index=False)
baseline_top_bottom_df.to_csv(OUTPUT_DIR / 'baseline_top_bottom_tokens.csv', index=False)
template_pair_df.to_csv(OUTPUT_DIR / 'template_pair_correlations.csv', index=False)
template_pair_rank_shift_df.to_csv(OUTPUT_DIR / 'template_pair_rank_shifts.csv', index=False)
print(f"Saved summary_correlations.csv ({len(summary_df)} rows)")
print(f"Saved rank_shifts.csv ({len(rank_shift_df)} rows)")
print(f"Saved top_bottom_tokens.csv ({len(top_bottom_df)} rows)")
print(f"Saved baseline_top_bottom_tokens.csv ({len(baseline_top_bottom_df)} rows)")
print(f"Saved template_pair_correlations.csv ({len(template_pair_df)} rows)")
print(f"Saved template_pair_rank_shifts.csv ({len(template_pair_rank_shift_df)} rows)")

if summary_df.empty:
    print("No data available yet — run generate_persona_reward_model_scores.py first.")
    sys.exit(0)

# ---------------------------------------------------------------------------
# Figure: Kendall's tau by persona, faceted by model x template
# ---------------------------------------------------------------------------
category_order = sorted(summary_df['persona_category'].unique())
palette = dict(zip(category_order, sns.color_palette('deep', n_colors=len(category_order))))

facets = summary_df.groupby(['model_nickname', 'template'])
n_facets = len(facets)
fig, axes = plt.subplots(n_facets, 1, figsize=(9, 3.2 * n_facets), squeeze=False)
axes = axes.ravel()

for ax, ((nickname, template), group) in zip(axes, facets):
    group = group.sort_values('kendall_tau')
    colors = [palette[c] for c in group['persona_category']]
    ax.barh(group['persona'], group['kendall_tau'], color=colors)
    ax.axvline(0, color='gray', linewidth=0.8)
    ax.set_title(f"{nickname} — {template}", fontsize=11)
    ax.set_xlabel("Kendall's tau vs. neutral baseline")
    ax.set_xlim(-1, 1)

handles = [plt.Rectangle((0, 0), 1, 1, color=palette[c]) for c in category_order]
fig.legend(handles, category_order, title="Persona category", loc='upper right', bbox_to_anchor=(1.15, 1))
plt.tight_layout()
fig.savefig(OUTPUT_DIR / 'fig_kendall_tau_by_persona.png', dpi=200, bbox_inches='tight')
plt.close(fig)
print("Saved fig_kendall_tau_by_persona.png")

# ---------------------------------------------------------------------------
# Figure: tau vs RBO(p=0.95) — spot high-tau/low-RBO or low-tau/high-RBO cases
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(7, 6))
for category in category_order:
    sub = summary_df[summary_df['persona_category'] == category]
    ax.scatter(sub['kendall_tau'], sub['rbo_p0.95'], label=category, color=palette[category], s=60, alpha=0.85)

ax.set_xlabel("Kendall's tau (whole-distribution agreement)")
ax.set_ylabel("RBO, p=0.95 (top-ranks agreement)")
ax.set_title("Whole-distribution vs. top-ranks agreement with neutral baseline")
ax.legend(title="Persona category", bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
fig.savefig(OUTPUT_DIR / 'fig_tau_vs_rbo.png', dpi=200, bbox_inches='tight')
plt.close(fig)
print("Saved fig_tau_vs_rbo.png")

# ---------------------------------------------------------------------------
# Figure: rank-shift example for the most-divergent (model, template, persona)
# ---------------------------------------------------------------------------
worst_row = summary_df.loc[summary_df['kendall_tau'].idxmin()]
example = rank_shift_df[
    (rank_shift_df['model_nickname'] == worst_row['model_nickname']) &
    (rank_shift_df['template'] == worst_row['template']) &
    (rank_shift_df['persona'] == worst_row['persona'])
].sort_values('rank_diff')

fig, ax = plt.subplots(figsize=(8, 8))
colors = ['#4575B4' if d < 0 else '#D73027' for d in example['rank_diff']]
ax.barh(example['token_decoded'].apply(format_token_label), example['rank_diff'], color=colors)
ax.axvline(0, color='black', linewidth=1)
ax.set_xlabel(f"Rank shift (persona rank − baseline rank)\n{worst_row['model_nickname']}, {worst_row['template']}, persona: \"{worst_row['persona']}\"")
ax.set_title("Tokens whose rank moved the most under this persona")
plt.tight_layout()
fig.savefig(OUTPUT_DIR / 'fig_rank_shift_example.png', dpi=200, bbox_inches='tight')
plt.close(fig)
print("Saved fig_rank_shift_example.png")

print("Done.")
